## 에러 처리

### 에러 처리의 필요성

- 에러가 발생하지 않는 코드를 작성하는 것은 불가능하기에 에러는 언제나 발생할 수 있음.
- 발생한 에러에 대해 대처하지 못한다면 프로그램은 강제 종료됨
- try...catch 문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있음
- 에러나 예외적인 상황은 너무나 다양하기 때문에 아무런 조치 없이 프로그램이 강제 종료된다면 원인을 파악하여 대응하기 어려움
- 언제나 에러나 예외적인 상황이 발생할 수 있다는 것을 전제하고 이에 대응하는 코드를 작성하는 것이 중요함.

### try... catch... finally 문

- 에러 처리를 위한 방법은 두가지가 있음
- 첫번째는 예외적인 상황이 발생하여 원하지 않는 값을 반환하는 것을 방지하는 방법(if문, 단축평가, 옵셔널 체이닝을 통해 확인 가능)
- 두번째는 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하는 방법
- try... catch... finally 문은 두번째 방법임. 일반적으로 이 방법을 에러 처리라고 함.
- 먼저 try 코드 블록이 실행됨. try 코드 블록에 포함된 문 중에서 에러가 발생하면 발생한 에러는 catch문의 err 변수에 전달되고 catch 코드 블록이 실행됨
- catch문의 err 변수는 try 코드 블록에 포함된 문 중에서 에러가 발생하면 생성되고 catch 코드 블록에서만 유효함.
- finally 코드 블록은 에러 발생과 상관없이 반드시 한번 실행됨

### Error 객체

- Error 생성자 함수는 에러 객체를 생성함. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있음
- Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 가짐.
- message 프로퍼티의 값은 Error 생성자 함수에 인수로 전달한 에러 메시지임
- stack 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열이며 디버깅 목적으로 사용함.
- JS는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공함.
- SyntaxError, ReferenceError, TypeError, RangeError, URIError, EvalError 생성자 함수가 생성한 에러 객체의 프로토타입은 모두 Error.prototype을 상속받음

| 생성자 함수    | 인스턴스                                                                       |
| -------------- | ------------------------------------------------------------------------------ |
| Error          | 일반적 에러 객체                                                               |
| SyntaxError    | JS 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체                          |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체                         |
| TypeError      | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체         |
| RangeError     | 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체                            |
| URIError       | encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError      | eval 함수에서 발생하는 에러 객체                                               |

### throw문

- Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아님. 에러 객체 생성과 에러 발생은 의미가 다름.
- 에러를 발생시키려면 try 코드 블록에서 throww문으로 에러 객체를 던져야함
- throw 문의 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정함. ex) throw new TypeEror('f must be a function')
- 에러를 던지면 catch 문의 에러 변수가 생성되고 던져진 에러 객체가 할당됨.

### 에러의 전파

- 에러는 호출자 방향으로 전파됨. 즉 콜 스택의 아래 방향으로 전파됨.
- throw된 에러를 캐치하지 않으면 호출자 방향으로 전파됨. 이 때 throw된 에러를 캐치하여 적절히 대응하면 코드의 실행 흐름을 복구할 수 있음
- throw된 에러를 어디서든 캐치하지 않으면 프로그램은 강제 종료됨.
- 비동기 함수나 프로미스 후속 처리 메서드의 콜백 함수는 태스크 큐나 마이크로태스크 큐에 일시적으로 저장되었다가 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행되는데, 이 때 콜 스택에 푸시된 콜백 함수의 실행 컨텍스틑 콜 스택의 가장 하부에 존재하게되어 에러를 전파할 호출자가 존재하지 않음.
